// <auto-generated />
using CEP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CEP.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190706135415_endereco")]
    partial class endereco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CEP.Models.Endereco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bairro");

                    b.Property<string>("cep");

                    b.Property<string>("complemento");

                    b.Property<string>("gia");

                    b.Property<string>("ibge");

                    b.Property<string>("localidade");

                    b.Property<string>("logradouro");

                    b.Property<string>("uf");

                    b.Property<string>("unidade");

                    b.HasKey("id");

                    b.ToTable("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
